[package]
name = "latka"
version = "0.0.1"
authors = ["Fenimore Love <exorable.ludos@gmail.com>"]
edition = "2018"


[dependencies]
bufstream = "0.1"
byteorder = "1"
getopts = "0.2.18"

[dev-dependencies]
speculate = "0.1.0"